import type {LinkData} from "./linksData.ts";

export const projects: LinkData[] = [
    // {
    //     url: "https",
    //     date: "24 Feb 2025",
    //     title: "title",
    //     comment: "comment",
    //     quote: "quote",
    //     tags: ['tag', 'tag'],
    // },
    {
        url: "https://pragprog.com/titles/aodjs/debugging-typescript-applications/",
        title: "Debugging TypeScript Applications: Build Web Apps That Don't Break",
        date: "2 Dec 2025",
        comment: "I wrote a book. It is in beta via Pragmatic Programmers",
        tags: ['book', 'writing'],
    },
    {
        url: "https://hightechmess.com/",
        date: "24 Mar 2024",
        title: "High Tech Mess",
        comment: "I organized a mini-festival of art and technologies",
        tags: ['music', 'event', 'live'],
    },
    {
        url: "https://youtu.be/Ytjqds8gVOU",
        date: "29 Jun 2024",
        title: "SP Sessions",
        comment: "I played live at Zürich made possible by 59perlen and Petite Victory Collective",
        tags: ['music', 'event', 'live'],
    },
    {
        url: "https://www.youtube.com/watch?v=FkCisgbQJQo",
        date: "20 Apr 2024",
        title: "Live stream with Teder",
        comment: "Improvised music for Nostr",
        tags: ['music', 'release'],
    },
    {
        url: "https://threecoloredsquares.bandcamp.com/track/zero-sum-game",
        date: "5 Apr 2024",
        title: "Zero-sum Game",
        comment: "I released Zero-Sum Game, an abstract trippy single drawing from trip-hop and downtempo electronica",
        tags: ['music', 'release'],
    },
    {
        url: "https://threecoloredsquares.bandcamp.com/track/novaya-zemlya",
        date: "1 Mar 2024",
        title: "Novaya Zemlya",
        comment: "I released Novaya Zemlya, equally influenced by contemporary classical and dance music",
        tags: ['music', 'release'],
    },
    {
        url: "https://oshibka404.github.io/cellular/",
        date: "11 Jan 2024",
        title: "Cellular",
        comment: "Small, fun and highly customizable ECA (elementary cellular automata) generator",
        tags: ['web'],
    },
    {
        url: "https://resonance.city",
        date: "11 Nov 2023",
        title: "Resonance City",
        comment: "Music sharing platform built with Next.js, PostgreSQL and Vercel",
        tags: ['music', 'web'],
    },
    {
        url: "https://www.youtube.com/watch?v=C-PYsEaGr8s",
        date: "11 Aug 2023",
        title: "Campana",
        comment: "Improvised music together with Teder",
        tags: ['music', 'live'],
    },
    {
        url: "https://threecoloredsquares.bandcamp.com/album/after-rain",
        date: "27 May 2022",
        title: "After Rain",
        comment: "The main theme of the album is leaving the place you love. “It was a way to reflect on the places I used to live in, on how they changed over time and how did I”. fully produced on Teenage Engineering OP-Z",
        tags: ['music', 'release'],
    },
    {
        url: "https://synt.ozorn.in/",
        date: "22 Sep 2020",
        title: "Cross-platform UI for Faust-based applications using Flutter",
        comment: "My talk on International Faust Conference 2020 about Faust",
        tags: ['faust', 'flutter', 'app', 'music', 'talk'],
    },
    {
        url: "https://github.com/oshibka404/faust_flutter",
        date: "28 Jun 2020",
        title: "Faust Flutter",
        comment: "A boilerplate template for a cross-platform audio application with DSP in Faust and UI in Dart/Flutter",
        tags: ['faust', 'dart', 'flutter', 'ios', 'app', 'dsp']
    },
    {
        url: "https://synt.ozorn.in/",
        date: "22 May 2020",
        title: "Synt",
        comment: "An iOS app you can play music with even if you think you can't",
        tags: ['faust', 'dart', 'flutter', 'ios', 'app', 'music'],
    },
]
